### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by GameboyColor32** [mat-1/azalea#91]
Sorry it might be a stupid question
I get a connection refused error in the echo bot example. I did open a local game to LAN, I can't really figure out what happens..

Thanks in advance and thanks for this awesome lib

**Comment by Iwyil** [comment]
Sorry for the dumb question, but just to check (I just had some problems myself recently):
- Did you check the port are the same? If you don't specify anything in the address (so you leave `"localhost"` in the echo.rs source) you should make minecraft listen on port 25565 when you open the world (this is the default for azalea)
- If you encounter some problems regarding version incompatibilities, know that the library on crates.io is outdated and not compatible with minecraft 1.20.1
- Otherwise, without more information on your system this is an almost impossible issue to troubleshoot

**Comment by GameboyColor32** [comment]
Thanks !
